# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sat Jan 18 13:03:08 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(907, 787)
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.propertyEditor = QtGui.QDockWidget(MainWindow)
        self.propertyEditor.setEnabled(True)
        self.propertyEditor.setMinimumSize(QtCore.QSize(200, 200))
        self.propertyEditor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.propertyEditor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.propertyEditor.setObjectName("propertyEditor")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.propertyEditor.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.propertyEditor)
        self.objectPallete = QtGui.QDockWidget(MainWindow)
        self.objectPallete.setEnabled(True)
        self.objectPallete.setMinimumSize(QtCore.QSize(200, 200))
        self.objectPallete.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.objectPallete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.objectPallete.setObjectName("objectPallete")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.objectPallete.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.objectPallete)
        self.environmentSettings = QtGui.QDockWidget(MainWindow)
        self.environmentSettings.setMinimumSize(QtCore.QSize(276, 270))
        self.environmentSettings.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.environmentSettings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.environmentSettings.setObjectName("environmentSettings")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 4, 1, 1)
        self.heightEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightEdit.sizePolicy().hasHeightForWidth())
        self.heightEdit.setSizePolicy(sizePolicy)
        self.heightEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.heightEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 1, 2, 1, 2)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.availableDevicesList = QtGui.QComboBox(self.dockWidgetContents_5)
        self.availableDevicesList.setObjectName("availableDevicesList")
        self.gridLayout.addWidget(self.availableDevicesList, 2, 2, 1, 1)
        self.updateDevicesBtn = QtGui.QToolButton(self.dockWidgetContents_5)
        self.updateDevicesBtn.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.updateDevicesBtn.setIcon(icon)
        self.updateDevicesBtn.setIconSize(QtCore.QSize(16, 16))
        self.updateDevicesBtn.setAutoRaise(False)
        self.updateDevicesBtn.setObjectName("updateDevicesBtn")
        self.gridLayout.addWidget(self.updateDevicesBtn, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.localAutoreload = QtGui.QCheckBox(self.dockWidgetContents_5)
        self.localAutoreload.setFocusPolicy(QtCore.Qt.TabFocus)
        self.localAutoreload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.localAutoreload.setObjectName("localAutoreload")
        self.gridLayout.addWidget(self.localAutoreload, 3, 2, 1, 1)
        self.deviceAutoreload = QtGui.QCheckBox(self.dockWidgetContents_5)
        self.deviceAutoreload.setFocusPolicy(QtCore.Qt.TabFocus)
        self.deviceAutoreload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deviceAutoreload.setObjectName("deviceAutoreload")
        self.gridLayout.addWidget(self.deviceAutoreload, 4, 2, 1, 1)
        self.reloadNowBtn = QtGui.QPushButton(self.dockWidgetContents_5)
        self.reloadNowBtn.setObjectName("reloadNowBtn")
        self.gridLayout.addWidget(self.reloadNowBtn, 6, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.widthEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.widthEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.widthEdit.setObjectName("widthEdit")
        self.gridLayout.addWidget(self.widthEdit, 0, 2, 1, 2)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.fullAutoreload = QtGui.QCheckBox(self.dockWidgetContents_5)
        self.fullAutoreload.setObjectName("fullAutoreload")
        self.gridLayout.addWidget(self.fullAutoreload, 5, 2, 1, 1)
        self.environmentSettings.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.environmentSettings)
        self.consoleOutput = QtGui.QDockWidget(MainWindow)
        self.consoleOutput.setObjectName("consoleOutput")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.localLogTab = QtGui.QWidget()
        self.localLogTab.setObjectName("localLogTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.localLogTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.localConsoleTextBox = QtGui.QTextEdit(self.localLogTab)
        self.localConsoleTextBox.setReadOnly(True)
        self.localConsoleTextBox.setObjectName("localConsoleTextBox")
        self.verticalLayout_2.addWidget(self.localConsoleTextBox)
        self.tabWidget.addTab(self.localLogTab, "")
        self.mobileLogTab = QtGui.QWidget()
        self.mobileLogTab.setObjectName("mobileLogTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mobileLogTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.deviceConsoleTextBox = QtGui.QTextEdit(self.mobileLogTab)
        self.deviceConsoleTextBox.setObjectName("deviceConsoleTextBox")
        self.verticalLayout_3.addWidget(self.deviceConsoleTextBox)
        self.tabWidget.addTab(self.mobileLogTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.consoleOutput.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.consoleOutput)
        self.actionOpen_project = QtGui.QAction(MainWindow)
        self.actionOpen_project.setObjectName("actionOpen_project")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSave_project = QtGui.QAction(MainWindow)
        self.actionSave_project.setObjectName("actionSave_project")
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionReload_Project = QtGui.QAction(MainWindow)
        self.actionReload_Project.setObjectName("actionReload_Project")
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addAction(self.actionOpen_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_project)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionReload_Project)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionOpen_project, QtCore.SIGNAL("triggered()"), MainWindow.showOpenFileDialog)
        QtCore.QObject.connect(self.reloadNowBtn, QtCore.SIGNAL("clicked()"), self.actionReload_Project.trigger)
        QtCore.QObject.connect(self.actionReload_Project, QtCore.SIGNAL("triggered()"), MainWindow.reloadMoai)
        QtCore.QObject.connect(self.localAutoreload, QtCore.SIGNAL("toggled(bool)"), MainWindow.setAutoreloadHost)
        QtCore.QObject.connect(self.deviceAutoreload, QtCore.SIGNAL("toggled(bool)"), MainWindow.setAutoreloadDevice)
        QtCore.QObject.connect(self.updateDevicesBtn, QtCore.SIGNAL("clicked()"), MainWindow.updateDeviceList)
        QtCore.QObject.connect(self.availableDevicesList, QtCore.SIGNAL("currentIndexChanged(int)"), MainWindow.setCurrentDevice)
        QtCore.QObject.connect(self.fullAutoreload, QtCore.SIGNAL("toggled(bool)"), MainWindow.setAutoreloadFull)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.widthEdit, self.heightEdit)
        MainWindow.setTabOrder(self.heightEdit, self.localAutoreload)
        MainWindow.setTabOrder(self.localAutoreload, self.deviceAutoreload)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.propertyEditor.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Property Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.objectPallete.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Object Palette", None, QtGui.QApplication.UnicodeUTF8))
        self.environmentSettings.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.updateDevicesBtn.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "AutoReload", None, QtGui.QApplication.UnicodeUTF8))
        self.localAutoreload.setText(QtGui.QApplication.translate("MainWindow", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceAutoreload.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadNowBtn.setText(QtGui.QApplication.translate("MainWindow", "Reload now", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.fullAutoreload.setText(QtGui.QApplication.translate("MainWindow", "Full reload", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleOutput.setWindowTitle(QtGui.QApplication.translate("MainWindow", "console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.localLogTab), QtGui.QApplication.translate("MainWindow", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mobileLogTab), QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_project.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_project.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_Project.setText(QtGui.QApplication.translate("MainWindow", "Reload Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
